### PR TITLE
Fix mouse cursor positioning on Linux.

### PR DESCRIPTION
**Pull request by taniwha**
This may be limited to Linux, but Event.current.mousePosition is sometimes
in line with Input.mousePosition and sometimes vertically inverted (needed
for rendering, it seems). Instead, use Input.mousePosition and do the
inversion locally.

### CODE REVIEW

**Comment by taniwha** [comment]
Sometime after doing the PR, I noticed that my update from your repo failed (because I couldn't equip EL's mallet), thus the merge in the PR. Sorry.

**Comment by ihsoft** [comment]
The problem is: `Input` works even when the game is in a windowed mode. Which will result in the hint repositioning even when the mouse pointer is out for the game window. I'd prefer to find the root cause of why the event is not reflecting the mouse position correctly. One idea is that not any type of the GUI events has this field set in Linux vs Windows. If this is the case, then simply a condition should be applied to only consider the mouse related events (clicks & moves + an initial setup on the hint creation). It will need some testing for which I don't have time as of now. Could you do this investigation?

**Comment by taniwha** [comment]
Ah, I never run KSP in anything but fullscreen mode, so I would not have noticed this. hmm, I wil indeed do some more investigation.

**Comment by taniwha** [comment]
I just tested my fix in a windowed KSP and there were no issues. The hint did not at all follow the mouse when the mouse was outside the window, nor was the hint offset from the mouse cursor while the mouse was in the window. I ensured that all four corners of the window were offset from the corners of the actual screen.

It seems that this may be the correct fix after all.

**Comment by taniwha** [comment]
If your issues with Input are caused by a windows bug, there's always Environment.OSVersion.Platform == PlatformID.Win32NT

**Comment by taniwha** [comment]
I have just discovered that the weird coordinate inversion is tied to key presses: mouse movements have top-down Y axis, but keyboard events have bottom-up Y axis, and because the G key must be held to drag a part into an inventory, Event.current.mousePosition bounced between mouse and keyboard coordinates with mouse motion and keyboard events (key repeat, I guess). Kerbal Alarm Clock suffers the same problem, but because no key+mouse dragging is done, it was easier to isolate the cause.

**Comment by ihsoft** [comment]
Thanks for the investigation! So, it sounds like my guess was right. The non-mouse events simply should not be used to get the mouse position, and it'll fix the issue. It makes sense.

**Pull request merged**
