### PR TITLE
Add parts from SEP

### PR DESCRIPTION
**Pull request by DanStaal**
Add utility parts from the defunct Surface Experiment Package mod.

Parts added:

- SEP_StorageLong (A large radial attach KIS container.)
- SEP_StorageShort (A small radial attach KIS container.)
- SEP_Box (A portable KIS container that folds up small in inventory.)
- SEP_FallenKerbonaut (A small tribute statue to leave behind.)

Signed-off-by: Daniel T. Staal <dstaal@usa.net>

### CODE REVIEW

**Comment by ihsoft** [comment]
Hey! Could you please add the images of the containers here? Just for the tracking :)

**Comment by DanStaal** [comment]
Is this what you're looking for?

The Cardboard Box (note that it can't be attached):
Cardboard_Box

The front of the lockers:
Lockers_Front

The back of the lockers (which embeds in parts):
Lockers_back

The Fallen Kerbonaut:
FallenKerbonaut

Full Set:
SEP_Parts

**Comment by ihsoft** [comment]
Yeah! This is it. Thanks!

Sorry, I'm a bit slow these days. Will merge this PR in the next version for sure.

**Comment by ihsoft** [comment]
I haven't found the fallen kerbonaut part in the PR. The other 3 parts were good.

**Comment by ihsoft** [comment]
Nevermind. The "missing" part was just located in the fun parts folder. All is good! Thanks.

**Comment by DanStaal** [comment]
Yeah, the fallen kerbonaut doesn't actually do anything, so I put it in with the fun parts.

**Pull request merged**
